### ISSUE TITLE
context for glide or picasso

### ISSUE THREAD

**Issue by SadeghTjk** [hereshem/Easy-RecyclerView-Library#1]
hi,
i cant use glide or picasso to load image in holder class because i dont have access to context or activity. 

itemView.getContext doesnt work.

any solution?

**Comment by hereshem** [comment]
How did you solved this problem. Let us know.

Though its easy to get context from any of the current view, 
if you have `TextView text` then
you can use `text.getContext()`

**Comment by SadeghTjk** [comment]
I found out its actually glide bug. i had to use . placeholder() to load the image.
like : 
Glide.with(tv.getContext()).load(url).placeholder(R.drawable.placeholder).into(imageview);

without placeholder, glide couldn't show the image!

**Comment by hereshem** [comment]
Thanks for the update
